### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by kinghows** [oltpbenchmark/website#11] opened 2017-06-13 02:11 UTC
1、auth_user.last_login chang to null
2、1146, "Table 'ottertune.django_session' doesn't exist"：
python manage.py makemigrations
python manage.py migrate

Then can create project and Application,What to do next?

**Comment by dvanaken** [comment] 2017-06-13 20:06
Duplicate of #10.

**Closed by dvanaken** 2017-06-13 20:06 UTC
